services:
  postgres:
    image: postgres:15
    container_name: basf_postgres
    environment:
      POSTGRES_DB: basf_data
      POSTGRES_USER: basf_user
      POSTGRES_PASSWORD: basf_secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - basf_db
    restart: unless-stopped

  api:
    build: .
    container_name: basf_api
    environment:
      DATABASE_URL: postgresql://basf_user:basf_secure_password_2024@postgres:5432/basf_data
    volumes:
      - ./src/api/data:/app/data
    depends_on:
      - postgres
    networks:
      - basf_internal
      - basf_db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: basf_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - basf_internal
    restart: unless-stopped

networks:
  basf_internal:
    driver: bridge
  basf_db:
    driver: bridge
    internal: true

volumes:
  postgres_data: